# Check https://circleci.com/docs/2.0/language-javascript/ for more details
 
version: 2
 
jobs:
 
  build:
 
    docker:
 
      # specify the version you desire here
 
      - image: circleci/node:12.19
 
      # Specify service dependencies here if necessary
 
      # CircleCI maintains a library of pre-built images
 
      # documented at https://circleci.com/docs/2.0/circleci-images/
 
      # the working dir is github repo that you need to fork to become owner.
 
    working_directory: https://github.com/GulamTest/16Dec.git
 
    steps:
 
      - checkout
      
      - run:
 
          name: "Setup custom environment variables // its your workflow step"
 
          command: |
 
            
 
      - run:
 
          name: "Setup custom environment variables"
 
          command: |
 
          
 
      - run: # Validating your above mentioned environment variables
 
          name: "gulama: "
 
          command: echo ${LT_USERNAME}      
 
      # Download and cache dependencies
 
      - restore_cache:
 
          keys:
 
            - v1-dependencies-{{ checksum "package.json" }}
 
            # fallback to using the latest cache if no exact match is found
 
      - run: npm install
 
      # run tests!
      - run: export LT_USERNAME= gulama
      - run: export LT_ACCESS_KEY= dvzmGKOrkoCTa9WLftEKObUX2S602F8FffTFApMstkLdN7BCfw
      - run: testcafe "lambdatest:Internet Explorer@11.0:Windows 10" "test.js"
